// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks_sale_affiliate_repository

import (
	context "context"

	customerror "github.com/beto-ouverney/go-affiliates/backend/internal/customerror"
	entities "github.com/beto-ouverney/go-affiliates/backend/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// ISaleAffiliateRepository is an autogenerated mock type for the ISaleAffiliateRepository type
type ISaleAffiliateRepository struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, s
func (_m *ISaleAffiliateRepository) Add(ctx context.Context, s []entities.Sale) *customerror.CustomError {
	ret := _m.Called(ctx, s)

	var r0 *customerror.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, []entities.Sale) *customerror.CustomError); ok {
		r0 = rf(ctx, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerror.CustomError)
		}
	}

	return r0
}

type mockConstructorTestingTNewISaleAffiliateRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewISaleAffiliateRepository creates a new instance of ISaleAffiliateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewISaleAffiliateRepository(t mockConstructorTestingTNewISaleAffiliateRepository) *ISaleAffiliateRepository {
	mock := &ISaleAffiliateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
