// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
  "basePath": "/api/v1",
  "definitions": {
    "sale": {
      "description": "the sale of the content producer/affiliate",
      "properties": {
        "affiliate": {
          "type": "string",
          "example": "GEORGE MARTIN"
        },
        "commission": {
          "type": "integer",
          "example": 1000
        },
        "date": {
          "type": "string",
          "example": "2022-01-15T19:20:30-03:00"
        },
        "producer": {
          "type": "string",
          "example": "ALBERTO PAZ"
        },
        "product": {
          "type": "string",
          "example": "CURSO DE GOLANG"
        },
        "value": {
          "type": "integer",
          "example": 2000
        }
      },
      "type": "object"
    },
    "response": {
      "description": "ResponseMsg response json message",
      "properties": {
        "message": {
          "type": "string",
          "example": "Any message from server"
        }
      },
      "type": "object"
    }
  },
  "host": "localhost:8088",
  "info": {
    "contact": {
      "name": "API Support",
      "url": "https://www.linkedin.com/in/beto-ouverney-paz/"
    },
    "description": "This is server to manager content producers and affiliates sales.",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "termsOfService": "http://swagger.io/terms/",
    "title": "Go Affiliates API",
    "version": "1.0"
  },
  "paths": {
    "/sales": {
      "get": {
        "description": "Get all sales of the content producers/affiliates from database",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "items": {
                "$ref": "#/definitions/sale"
              },
              "type": "array"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/response"
            }
          }
        },
        "summary": "Get sales from database"
      }
    },
    "/sales/upload": {
      "post": {
        "description": "Receive a file with sales and add all in database",
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "formData",
            "name": "file",
            "description": "file contains all sales. The file must be a text file.",
            "type": "file*"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "examples": {
              "application/json": {
                "message": "Sales added successfully"
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/response"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/response"
            }
          }
        },
        "summary": "Add sales to database"
      }
    }
  },
  "swagger": "2.0"
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8088",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Go Affiliates API",
	Description:      "This is server to manager content producers and affiliates sales.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
