// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	customerror "github.com/beto-ouverney/go-affiliates/backend/internal/customerror"
	entities "github.com/beto-ouverney/go-affiliates/backend/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// ISalesUseCase is an autogenerated mock type for the ISalesUseCase type
type ISalesUseCase struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, nameFile
func (_m *ISalesUseCase) Add(ctx context.Context, nameFile string) *customerror.CustomError {
	ret := _m.Called(ctx, nameFile)

	var r0 *customerror.CustomError
	if rf, ok := ret.Get(0).(func(context.Context, string) *customerror.CustomError); ok {
		r0 = rf(ctx, nameFile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerror.CustomError)
		}
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *ISalesUseCase) GetAll(ctx context.Context) (*[]entities.SaleResponse, *customerror.CustomError) {
	ret := _m.Called(ctx)

	var r0 *[]entities.SaleResponse
	if rf, ok := ret.Get(0).(func(context.Context) *[]entities.SaleResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entities.SaleResponse)
		}
	}

	var r1 *customerror.CustomError
	if rf, ok := ret.Get(1).(func(context.Context) *customerror.CustomError); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*customerror.CustomError)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewISalesUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewISalesUseCase creates a new instance of ISalesUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewISalesUseCase(t mockConstructorTestingTNewISalesUseCase) *ISalesUseCase {
	mock := &ISalesUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
