// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks_sales_usecase

import mock "github.com/stretchr/testify/mock"

// typeSet is an autogenerated mock type for the typeSet type
type typeSet struct {
	mock.Mock
}

type mockConstructorTestingTnewTypeSet interface {
	mock.TestingT
	Cleanup(func())
}

// newTypeSet creates a new instance of typeSet. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newTypeSet(t mockConstructorTestingTnewTypeSet) *typeSet {
	mock := &typeSet{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
