// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks_affiliate_repository

import (
	context "context"

	customerror "github.com/beto-ouverney/go-affiliates/backend/internal/customerror"
	entities "github.com/beto-ouverney/go-affiliates/backend/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// IAffiliateRepository is an autogenerated mock type for the IAffiliateRepository type
type IAffiliateRepository struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, name, producer_id
func (_m *IAffiliateRepository) Add(ctx context.Context, name string, producer_id int64) (*int64, *customerror.CustomError) {
	ret := _m.Called(ctx, name, producer_id)

	var r0 *int64
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) *int64); ok {
		r0 = rf(ctx, name, producer_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int64)
		}
	}

	var r1 *customerror.CustomError
	if rf, ok := ret.Get(1).(func(context.Context, string, int64) *customerror.CustomError); ok {
		r1 = rf(ctx, name, producer_id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*customerror.CustomError)
		}
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *IAffiliateRepository) GetByName(ctx context.Context, name string) (*entities.Affiliate, *customerror.CustomError) {
	ret := _m.Called(ctx, name)

	var r0 *entities.Affiliate
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Affiliate); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Affiliate)
		}
	}

	var r1 *customerror.CustomError
	if rf, ok := ret.Get(1).(func(context.Context, string) *customerror.CustomError); ok {
		r1 = rf(ctx, name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*customerror.CustomError)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewIAffiliateRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewIAffiliateRepository creates a new instance of IAffiliateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIAffiliateRepository(t mockConstructorTestingTNewIAffiliateRepository) *IAffiliateRepository {
	mock := &IAffiliateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
